Node *correct_borders_parents(Arguments *args, Node *local_tree, ulong *dims) ;
void correct_borders_att(Arguments *args, Node *local_tree, ulong *dims, AuxDataStore *store);
Node *correct_local_tree_par(Node *local_tree, Boundary *b);
void correct_local_tree_att(Node *local_tree, Boundary *b, AuxDataStore *store);
Boundary *update_par(Boundary *b, Boundary *c) ;
Boundary *update_branch_par(BorderIndex x, BorderIndex z, BorderIndex s);
void *update_att(Boundary *a, Boundary *b, Boundary *c);
Boundary *adding_node_par(BorderIndex x, BorderIndex s) ;
Boundary *combine_step(Boundary *a, Boundary *b, Direction d, int step) ;
void b_add_step(Boundary *c, Boundary *b, ulong s, ulong i, int step) ;
void merge_step(Boundary *a, Boundary *b, Direction d, int step) ;
void merge_b_nodes_par(BorderIndex x, BorderIndex y);
void merge_b_nodes_attr(BorderIndex x, BorderIndex y);
Boundary *create_boundary_parents(Node* local_tree, ulong *dims, int connectivity);
Boundary *create_boundary_att(Node* local_tree, ulong *dims, int attrib_choice, int connectivity);
void add_side_par(Node *local_tree, Boundary *b, int side, ulong *length, ulong offset, ulong *offset_bd, long *increment, int connectivity);
Boundary *add_ancestors_par(Node *local_tree, Boundary *b) ;
void node_to_bound_par(Node *local_tree, Boundary *b, ulong b_idx, ulong tree_idx);
void bound_to_tree_par(Node *local_tree, Boundary *b, ulong b_idx, ulong tree_idx);
Boundary *realloc_b_par(Boundary *b, ulong size_tree_new);
void free_boundary_par(Boundary *b) ;
