/*
  File autogenerated by gengetopt version 2.23
  generated with the following command:
  gengetopt 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "This program filters 1D, 2D or 3D images using distributed-memory parallel\ncomputation of max-trees";

const char *gengetopt_args_info_usage = "Usage: Area/DAP/Pattern spectrum [OPTION]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "Area: Input files are expected to be preprocessed into tiles of the form\n[inprefix]-[x].[intype], e.g. tile-1.pgm to tile-8.pgm for a 2x2x2 grid. HDF5\nfiles can be used (name should be [inprefix].h5).\nFits images can be used (name should be [inprefix].fits). Output files will be\ngenerated following the same grid with [outprefix]-[x].[outtype], e.g.\nout-1.pgm to out-8.pgm for typical images format,\nHDF5 files will be saved as [outprefix].h5 and fits images as [outprefix].fits.\n \nCSL: Three external output will be produced, the contrast output (C), the\nluminance (L), and the scale (S).\nPattern: Only one output is produced, the pattern.txt file.";

const char *gengetopt_args_info_help[] = {
  "  -h, --help               Print help and exit",
  "  -V, --version            Print version and exit",
  "\nFilename handling:",
  "These options select the prefix of the in- and output tiles, as well as the\nfiletype and dataset name for HDF5 files",
  "      --inprefix=STRING    Prefix of the filenames of input tiles\n                             (default=`tile')",
  "      --outprefix=STRING   Prefix of the filenames for the output tiles\n                             (default=`out')",
  "      --intype=STRING      filetype of the input tiles  (default=`pgm')",
  "      --outtype=STRING     filetype of the output tiles",
  "      --infile=INT         Define how the input files are organized. 0: 1 file\n                             to be divided internally, 1: Each process takes a\n                             different file (see expected format names), 2:\n                             same file copied on all processes, 3: Combine RBG\n                             files  (default=`0')",
  "      --outfile=INT        Define how the output files are organized. 0: 1\n                             single file is written, 2: Each process writes his\n                             tile (see expected format names)",
  "      --dataset=STRING     Name of the dataset if using HDF5 files",
  "  -s, --saveout=INT        Save the output images. In case it needs to be\n                             deactivated for testing purposes  (possible\n                             values=\"0\", \"1\" default=`1')",
  "      --overlap=INT        Save the output images. In case it needs to be\n                             deactivated for testing purposes  (possible\n                             values=\"0\", \"1\" default=`1')",
  "The --grid (-g) option takes a three comma separated values which controls the\nnumber of expected horizontal, vertical and in depth tiles. The --threads\noption define the number of threads used for \nlocal building and filtering of the trees (maximum 128)",
  "\nTiles:",
  "  -g, --grid=INT           Number of tiles horizontally, vertically, in depth,\n                             comma separated",
  "      --threads=INT        Number of threads to use  (default=`1')",
  "\nImage options:",
  "  -b, --bpp=INT            Define the dynamic range (if different from 8, 16 or\n                             32 bits)  (default=`8')",
  "  -r, --refine=INT         Transform the data in 16-bit per pixel if original\n                             range is higher  (default=`0')",
  "      --image=STRING       Type of input: classic, rgb, lofar, sequence of 2D\n                             tiles to be combined internally\n                             (default=`classic')",
  "      --negative=INT       Transform the data in 16-bit per pixel if original\n                             range is higher  (default=`0')",
  "\nFilter options:",
  "  -a, --attribute=INT      Choose the attribute to build the tree\n                             (default=`0')",
  "      --attribute2=INT     Choose the second attribute for the pattern spectrum\n                             (only works with the inertia tensor so far)\n                             (default=`9')",
  "  -d, --decision=INT       Choose the pruning rule to filter the tree\n                             (default=`0')",
  "  -f, --flood=INT          Choose the used flooding technique (deprecated).\n                             (possible values=\"0\", \"1\", \"2\" default=`0')",
  "  -o, --output=STRING      Choose the desired output  (possible\n                             values=\"filter\", \"csl\", \"pattern\",\n                             \"pattern2d\", \"eor\", \"test\", \"tree\",\n                             \"som\", \"none\" default=`filter')",
  "  -l, --lambda=DOUBLE      Lambda value  (default=`100')",
  "      --lvec=STRING        Lambda vector for  attribute\n                             (default=`res/lvec.txt')",
  "      --lvec2=STRING       Lambda vector for second attribute\n                             (default=`res/lvec2.txt')",
  "  -t, --tree=STRING        Type of tree (Min or Max)  (possible values=\"min\",\n                             \"max\" default=`max')",
  "  -m, --morphology=STRING  Type of morphological operation (opening or closing)\n                             (possible values=\"opening\", \"closing\"\n                             default=`opening')",
  "  -c, --connectivity=INT   Type of connectivity (4 or 8 for 2D, 6 or 26 for 3D)\n                             (possible values=\"4\", \"8\", \"6\", \"26\"\n                             default=`4')",
  "      --imscale=FLOAT      Scale for lvec file  (default=`1.0')",
  "      --imscale2=FLOAT     Scale for lvec2 file  (default=`1.0')",
  "      --background=INT     Account for background level in the pattern spectra\n                             (default=`0')",
  "\nOther options:",
  "  -v, --verbosity=STRING   Add verbose output  (possible values=\"OFF\",\n                             \"off\", \"ERROR\", \"error\", \"WARN\", \"warn\",\n                             \"INFO\", \"info\", \"DEBUG\", \"debug\",\n                             \"TRACE\", \"trace\", \"TIMING\", \"timing\",\n                             \"ALL\", \"all\" default=`WARN')",
  "      --savetree=INT       Save the component tree. Each process will save its\n                             local tree, so it can be reused later (the same\n                             number of process will have to be used)  (possible\n                             values=\"0\", \"1\" default=`0')",
  "      --somfile=STRING     Save the component tree. Each process will save its\n                             local tree, so it can be reused later (the same\n                             number of process will have to be used)",
  "      --somsize=INT        Save the component tree. Each process will save its\n                             local tree, so it can be reused later (the same\n                             number of process will have to be used)",
  "      --somneuron=INT      Number of tiles horizontally, vertically, in depth,\n                             comma separated",
    0
};

typedef enum {ARG_NO
  , ARG_STRING
  , ARG_INT
  , ARG_FLOAT
  , ARG_DOUBLE
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

const char *cmdline_parser_saveout_values[] = {"0", "1", 0}; /*< Possible values for saveout. */
const char *cmdline_parser_overlap_values[] = {"0", "1", 0}; /*< Possible values for overlap. */
const char *cmdline_parser_flood_values[] = {"0", "1", "2", 0}; /*< Possible values for flood. */
const char *cmdline_parser_output_values[] = {"filter", "csl", "pattern", "pattern2d", "eor", "test", "tree", "som", "none", 0}; /*< Possible values for output. */
const char *cmdline_parser_tree_values[] = {"min", "max", 0}; /*< Possible values for tree. */
const char *cmdline_parser_morphology_values[] = {"opening", "closing", 0}; /*< Possible values for morphology. */
const char *cmdline_parser_connectivity_values[] = {"4", "8", "6", "26", 0}; /*< Possible values for connectivity. */
const char *cmdline_parser_verbosity_values[] = {"OFF", "off", "ERROR", "error", "WARN", "warn", "INFO", "info", "DEBUG", "debug", "TRACE", "trace", "TIMING", "timing", "ALL", "all", 0}; /*< Possible values for verbosity. */
const char *cmdline_parser_savetree_values[] = {"0", "1", 0}; /*< Possible values for savetree. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->inprefix_given = 0 ;
  args_info->outprefix_given = 0 ;
  args_info->intype_given = 0 ;
  args_info->outtype_given = 0 ;
  args_info->infile_given = 0 ;
  args_info->outfile_given = 0 ;
  args_info->dataset_given = 0 ;
  args_info->saveout_given = 0 ;
  args_info->overlap_given = 0 ;
  args_info->grid_given = 0 ;
  args_info->threads_given = 0 ;
  args_info->bpp_given = 0 ;
  args_info->refine_given = 0 ;
  args_info->image_given = 0 ;
  args_info->negative_given = 0 ;
  args_info->attribute_given = 0 ;
  args_info->attribute2_given = 0 ;
  args_info->decision_given = 0 ;
  args_info->flood_given = 0 ;
  args_info->output_given = 0 ;
  args_info->lambda_given = 0 ;
  args_info->lvec_given = 0 ;
  args_info->lvec2_given = 0 ;
  args_info->tree_given = 0 ;
  args_info->morphology_given = 0 ;
  args_info->connectivity_given = 0 ;
  args_info->imscale_given = 0 ;
  args_info->imscale2_given = 0 ;
  args_info->background_given = 0 ;
  args_info->verbosity_given = 0 ;
  args_info->savetree_given = 0 ;
  args_info->somfile_given = 0 ;
  args_info->somsize_given = 0 ;
  args_info->somneuron_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->inprefix_arg = gengetopt_strdup ("tile");
  args_info->inprefix_orig = NULL;
  args_info->outprefix_arg = gengetopt_strdup ("out");
  args_info->outprefix_orig = NULL;
  args_info->intype_arg = gengetopt_strdup ("pgm");
  args_info->intype_orig = NULL;
  args_info->outtype_arg = NULL;
  args_info->outtype_orig = NULL;
  args_info->infile_arg = 0;
  args_info->infile_orig = NULL;
  args_info->outfile_orig = NULL;
  args_info->dataset_arg = NULL;
  args_info->dataset_orig = NULL;
  args_info->saveout_arg = 1;
  args_info->saveout_orig = NULL;
  args_info->overlap_arg = 1;
  args_info->overlap_orig = NULL;
  args_info->grid_arg = NULL;
  args_info->grid_orig = NULL;
  args_info->threads_arg = 1;
  args_info->threads_orig = NULL;
  args_info->bpp_arg = 8;
  args_info->bpp_orig = NULL;
  args_info->refine_arg = 0;
  args_info->refine_orig = NULL;
  args_info->image_arg = gengetopt_strdup ("classic");
  args_info->image_orig = NULL;
  args_info->negative_arg = 0;
  args_info->negative_orig = NULL;
  args_info->attribute_arg = 0;
  args_info->attribute_orig = NULL;
  args_info->attribute2_arg = 9;
  args_info->attribute2_orig = NULL;
  args_info->decision_arg = 0;
  args_info->decision_orig = NULL;
  args_info->flood_arg = 0;
  args_info->flood_orig = NULL;
  args_info->output_arg = gengetopt_strdup ("filter");
  args_info->output_orig = NULL;
  args_info->lambda_arg = 100;
  args_info->lambda_orig = NULL;
  args_info->lvec_arg = gengetopt_strdup ("res/lvec.txt");
  args_info->lvec_orig = NULL;
  args_info->lvec2_arg = gengetopt_strdup ("res/lvec2.txt");
  args_info->lvec2_orig = NULL;
  args_info->tree_arg = gengetopt_strdup ("max");
  args_info->tree_orig = NULL;
  args_info->morphology_arg = gengetopt_strdup ("opening");
  args_info->morphology_orig = NULL;
  args_info->connectivity_arg = 4;
  args_info->connectivity_orig = NULL;
  args_info->imscale_arg = 1.0;
  args_info->imscale_orig = NULL;
  args_info->imscale2_arg = 1.0;
  args_info->imscale2_orig = NULL;
  args_info->background_arg = 0;
  args_info->background_orig = NULL;
  args_info->verbosity_arg = gengetopt_strdup ("WARN");
  args_info->verbosity_orig = NULL;
  args_info->savetree_arg = 0;
  args_info->savetree_orig = NULL;
  args_info->somfile_arg = NULL;
  args_info->somfile_orig = NULL;
  args_info->somsize_orig = NULL;
  args_info->somneuron_arg = NULL;
  args_info->somneuron_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->inprefix_help = gengetopt_args_info_help[4] ;
  args_info->outprefix_help = gengetopt_args_info_help[5] ;
  args_info->intype_help = gengetopt_args_info_help[6] ;
  args_info->outtype_help = gengetopt_args_info_help[7] ;
  args_info->infile_help = gengetopt_args_info_help[8] ;
  args_info->outfile_help = gengetopt_args_info_help[9] ;
  args_info->dataset_help = gengetopt_args_info_help[10] ;
  args_info->saveout_help = gengetopt_args_info_help[11] ;
  args_info->overlap_help = gengetopt_args_info_help[12] ;
  args_info->grid_help = gengetopt_args_info_help[15] ;
  args_info->grid_min = 3;
  args_info->grid_max = 3;
  args_info->threads_help = gengetopt_args_info_help[16] ;
  args_info->bpp_help = gengetopt_args_info_help[18] ;
  args_info->refine_help = gengetopt_args_info_help[19] ;
  args_info->image_help = gengetopt_args_info_help[20] ;
  args_info->negative_help = gengetopt_args_info_help[21] ;
  args_info->attribute_help = gengetopt_args_info_help[23] ;
  args_info->attribute2_help = gengetopt_args_info_help[24] ;
  args_info->decision_help = gengetopt_args_info_help[25] ;
  args_info->flood_help = gengetopt_args_info_help[26] ;
  args_info->output_help = gengetopt_args_info_help[27] ;
  args_info->lambda_help = gengetopt_args_info_help[28] ;
  args_info->lvec_help = gengetopt_args_info_help[29] ;
  args_info->lvec2_help = gengetopt_args_info_help[30] ;
  args_info->tree_help = gengetopt_args_info_help[31] ;
  args_info->morphology_help = gengetopt_args_info_help[32] ;
  args_info->connectivity_help = gengetopt_args_info_help[33] ;
  args_info->imscale_help = gengetopt_args_info_help[34] ;
  args_info->imscale2_help = gengetopt_args_info_help[35] ;
  args_info->background_help = gengetopt_args_info_help[36] ;
  args_info->verbosity_help = gengetopt_args_info_help[38] ;
  args_info->savetree_help = gengetopt_args_info_help[39] ;
  args_info->somfile_help = gengetopt_args_info_help[40] ;
  args_info->somsize_help = gengetopt_args_info_help[41] ;
  args_info->somneuron_help = gengetopt_args_info_help[42] ;
  args_info->somneuron_min = 2;
  args_info->somneuron_max = 2;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void)
{
	size_t len_purpose = strlen(gengetopt_args_info_purpose);
	size_t len_usage = strlen(gengetopt_args_info_usage);

	if (len_usage > 0) {
		printf("%s\n", gengetopt_args_info_usage);
	}
	if (len_purpose > 0) {
		printf("%s\n", gengetopt_args_info_purpose);
	}

	if (len_usage || len_purpose) {
		printf("\n");
	}

	if (strlen(gengetopt_args_info_description) > 0) {
		printf("%s\n\n", gengetopt_args_info_description);
	}
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}

/** @brief generic value variable */
union generic_value {
    int int_arg;
    float float_arg;
    double double_arg;
    char *string_arg;
    const char *default_string_arg;
};

/** @brief holds temporary values for multiple options */
struct generic_list
{
  union generic_value arg;
  char *orig;
  struct generic_list *next;
};

/**
 * @brief add a node at the head of the list 
 */
static void add_node(struct generic_list **list) {
  struct generic_list *new_node = (struct generic_list *) malloc (sizeof (struct generic_list));
  new_node->next = *list;
  *list = new_node;
  new_node->arg.string_arg = 0;
  new_node->orig = 0;
}

/**
 * The passed arg parameter is NOT set to 0 from this function
 */
static void
free_multiple_field(unsigned int len, void *arg, char ***orig)
{
  unsigned int i;
  if (arg) {
    for (i = 0; i < len; ++i)
      {
        free_string_field(&((*orig)[i]));
      }

    free (arg);
    free (*orig);
    *orig = 0;
  }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->inprefix_arg));
  free_string_field (&(args_info->inprefix_orig));
  free_string_field (&(args_info->outprefix_arg));
  free_string_field (&(args_info->outprefix_orig));
  free_string_field (&(args_info->intype_arg));
  free_string_field (&(args_info->intype_orig));
  free_string_field (&(args_info->outtype_arg));
  free_string_field (&(args_info->outtype_orig));
  free_string_field (&(args_info->infile_orig));
  free_string_field (&(args_info->outfile_orig));
  free_string_field (&(args_info->dataset_arg));
  free_string_field (&(args_info->dataset_orig));
  free_string_field (&(args_info->saveout_orig));
  free_string_field (&(args_info->overlap_orig));
  free_multiple_field (args_info->grid_given, (void *)(args_info->grid_arg), &(args_info->grid_orig));
  args_info->grid_arg = 0;
  free_string_field (&(args_info->threads_orig));
  free_string_field (&(args_info->bpp_orig));
  free_string_field (&(args_info->refine_orig));
  free_string_field (&(args_info->image_arg));
  free_string_field (&(args_info->image_orig));
  free_string_field (&(args_info->negative_orig));
  free_string_field (&(args_info->attribute_orig));
  free_string_field (&(args_info->attribute2_orig));
  free_string_field (&(args_info->decision_orig));
  free_string_field (&(args_info->flood_orig));
  free_string_field (&(args_info->output_arg));
  free_string_field (&(args_info->output_orig));
  free_string_field (&(args_info->lambda_orig));
  free_string_field (&(args_info->lvec_arg));
  free_string_field (&(args_info->lvec_orig));
  free_string_field (&(args_info->lvec2_arg));
  free_string_field (&(args_info->lvec2_orig));
  free_string_field (&(args_info->tree_arg));
  free_string_field (&(args_info->tree_orig));
  free_string_field (&(args_info->morphology_arg));
  free_string_field (&(args_info->morphology_orig));
  free_string_field (&(args_info->connectivity_orig));
  free_string_field (&(args_info->imscale_orig));
  free_string_field (&(args_info->imscale2_orig));
  free_string_field (&(args_info->background_orig));
  free_string_field (&(args_info->verbosity_arg));
  free_string_field (&(args_info->verbosity_orig));
  free_string_field (&(args_info->savetree_orig));
  free_string_field (&(args_info->somfile_arg));
  free_string_field (&(args_info->somfile_orig));
  free_string_field (&(args_info->somsize_orig));
  free_multiple_field (args_info->somneuron_given, (void *)(args_info->somneuron_arg), &(args_info->somneuron_orig));
  args_info->somneuron_arg = 0;
  
  

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}

static void
write_multiple_into_file(FILE *outfile, int len, const char *opt, char **arg, const char *values[])
{
  int i;
  
  for (i = 0; i < len; ++i)
    write_into_file(outfile, opt, (arg ? arg[i] : 0), values);
}

int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->inprefix_given)
    write_into_file(outfile, "inprefix", args_info->inprefix_orig, 0);
  if (args_info->outprefix_given)
    write_into_file(outfile, "outprefix", args_info->outprefix_orig, 0);
  if (args_info->intype_given)
    write_into_file(outfile, "intype", args_info->intype_orig, 0);
  if (args_info->outtype_given)
    write_into_file(outfile, "outtype", args_info->outtype_orig, 0);
  if (args_info->infile_given)
    write_into_file(outfile, "infile", args_info->infile_orig, 0);
  if (args_info->outfile_given)
    write_into_file(outfile, "outfile", args_info->outfile_orig, 0);
  if (args_info->dataset_given)
    write_into_file(outfile, "dataset", args_info->dataset_orig, 0);
  if (args_info->saveout_given)
    write_into_file(outfile, "saveout", args_info->saveout_orig, cmdline_parser_saveout_values);
  if (args_info->overlap_given)
    write_into_file(outfile, "overlap", args_info->overlap_orig, cmdline_parser_overlap_values);
  write_multiple_into_file(outfile, args_info->grid_given, "grid", args_info->grid_orig, 0);
  if (args_info->threads_given)
    write_into_file(outfile, "threads", args_info->threads_orig, 0);
  if (args_info->bpp_given)
    write_into_file(outfile, "bpp", args_info->bpp_orig, 0);
  if (args_info->refine_given)
    write_into_file(outfile, "refine", args_info->refine_orig, 0);
  if (args_info->image_given)
    write_into_file(outfile, "image", args_info->image_orig, 0);
  if (args_info->negative_given)
    write_into_file(outfile, "negative", args_info->negative_orig, 0);
  if (args_info->attribute_given)
    write_into_file(outfile, "attribute", args_info->attribute_orig, 0);
  if (args_info->attribute2_given)
    write_into_file(outfile, "attribute2", args_info->attribute2_orig, 0);
  if (args_info->decision_given)
    write_into_file(outfile, "decision", args_info->decision_orig, 0);
  if (args_info->flood_given)
    write_into_file(outfile, "flood", args_info->flood_orig, cmdline_parser_flood_values);
  if (args_info->output_given)
    write_into_file(outfile, "output", args_info->output_orig, cmdline_parser_output_values);
  if (args_info->lambda_given)
    write_into_file(outfile, "lambda", args_info->lambda_orig, 0);
  if (args_info->lvec_given)
    write_into_file(outfile, "lvec", args_info->lvec_orig, 0);
  if (args_info->lvec2_given)
    write_into_file(outfile, "lvec2", args_info->lvec2_orig, 0);
  if (args_info->tree_given)
    write_into_file(outfile, "tree", args_info->tree_orig, cmdline_parser_tree_values);
  if (args_info->morphology_given)
    write_into_file(outfile, "morphology", args_info->morphology_orig, cmdline_parser_morphology_values);
  if (args_info->connectivity_given)
    write_into_file(outfile, "connectivity", args_info->connectivity_orig, cmdline_parser_connectivity_values);
  if (args_info->imscale_given)
    write_into_file(outfile, "imscale", args_info->imscale_orig, 0);
  if (args_info->imscale2_given)
    write_into_file(outfile, "imscale2", args_info->imscale2_orig, 0);
  if (args_info->background_given)
    write_into_file(outfile, "background", args_info->background_orig, 0);
  if (args_info->verbosity_given)
    write_into_file(outfile, "verbosity", args_info->verbosity_orig, cmdline_parser_verbosity_values);
  if (args_info->savetree_given)
    write_into_file(outfile, "savetree", args_info->savetree_orig, cmdline_parser_savetree_values);
  if (args_info->somfile_given)
    write_into_file(outfile, "somfile", args_info->somfile_orig, 0);
  if (args_info->somsize_given)
    write_into_file(outfile, "somsize", args_info->somsize_orig, 0);
  write_multiple_into_file(outfile, args_info->somneuron_given, "somneuron", args_info->somneuron_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  const char *tok;
  char *ret;
  size_t len, num_of_escape, i, j;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');
  num_of_escape = 0;

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
          ++num_of_escape;
        }
      else
        break;
    }

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  len -= num_of_escape;

  ret = (char *) malloc (len);

  i = 0;
  j = 0;
  while (arg[i] && (j < len-1))
    {
      if (arg[i] == '\\' && 
	  arg[ i + 1 ] && 
	  arg[ i + 1 ] == ',')
        ++i;

      ret[j++] = arg[i++];
    }

  ret[len-1] = '\0';

  return ret;
}

static const char *
get_multiple_arg_token_next(const char *arg)
{
  const char *tok;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
        }
      else
        break;
    }

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc)
{
  int error_occurred = 0;

  if (option_given && (min > 0 || max > 0))
    {
      if (min > 0 && max > 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != (unsigned int) min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error_occurred = 1;
                }
            }
          else if (option_given < (unsigned int) min
                || option_given > (unsigned int) max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error_occurred = 1;
            }
        }
      else if (min > 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error_occurred = 1;
            }
        }
      else if (max > 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error_occurred = 1;
            }
        }
    }
    
  return error_occurred;
}
int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (! args_info->grid_given)
    {
      fprintf (stderr, "%s: '--grid' ('-g') option required%s\n", prog_name, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  
  if (check_multiple_option_occurrences(prog_name, args_info->grid_given, args_info->grid_min, args_info->grid_max, "'--grid' ('-g')"))
     error_occurred = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->somneuron_given, args_info->somneuron_min, args_info->somneuron_max, "'--somneuron'"))
     error_occurred = 1;
  
  
  /* checks for dependences among options */

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_FLOAT:
    if (val) *((float *)field) = (float)strtod (val, &stop_char);
    break;
  case ARG_DOUBLE:
    if (val) *((double *)field) = strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_FLOAT:
  case ARG_DOUBLE:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}

/**
 * @brief store information about a multiple option in a temporary list
 * @param list where to (temporarily) store multiple options
 */
static
int update_multiple_arg_temp(struct generic_list **list,
               unsigned int *prev_given, const char *val,
               const char *possible_values[], const char *default_value,
               cmdline_parser_arg_type arg_type,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  /* store single arguments */
  char *multi_token;
  const char *multi_next;

  if (arg_type == ARG_NO) {
    (*prev_given)++;
    return 0; /* OK */
  }

  multi_token = get_multiple_arg_token(val);
  multi_next = get_multiple_arg_token_next (val);

  while (1)
    {
      add_node (list);
      if (update_arg((void *)&((*list)->arg), &((*list)->orig), 0,
          prev_given, multi_token, possible_values, default_value, 
          arg_type, 0, 1, 1, 1, long_opt, short_opt, additional_error)) {
        if (multi_token) free(multi_token);
        return 1; /* failure */
      }

      if (multi_next)
        {
          multi_token = get_multiple_arg_token(multi_next);
          multi_next = get_multiple_arg_token_next (multi_next);
        }
      else
        break;
    }

  return 0; /* OK */
}

/**
 * @brief free the passed list (including possible string argument)
 */
static
void free_list(struct generic_list *list, short string_arg)
{
  if (list) {
    struct generic_list *tmp;
    while (list)
      {
        tmp = list;
        if (string_arg && list->arg.string_arg)
          free (list->arg.string_arg);
        if (list->orig)
          free (list->orig);
        list = list->next;
        free (tmp);
      }
  }
}

/**
 * @brief updates a multiple option starting from the passed list
 */
static
void update_multiple_arg(void *field, char ***orig_field,
               unsigned int field_given, unsigned int prev_given, union generic_value *default_value,
               cmdline_parser_arg_type arg_type,
               struct generic_list *list)
{
  int i;
  struct generic_list *tmp;

  if (prev_given && list) {
    *orig_field = (char **) realloc (*orig_field, (field_given + prev_given) * sizeof (char *));

    switch(arg_type) {
    case ARG_INT:
      *((int **)field) = (int *)realloc (*((int **)field), (field_given + prev_given) * sizeof (int)); break;
    case ARG_FLOAT:
      *((float **)field) = (float *)realloc (*((float **)field), (field_given + prev_given) * sizeof (float)); break;
    case ARG_DOUBLE:
      *((double **)field) = (double *)realloc (*((double **)field), (field_given + prev_given) * sizeof (double)); break;
    case ARG_STRING:
      *((char ***)field) = (char **)realloc (*((char ***)field), (field_given + prev_given) * sizeof (char *)); break;
    default:
      break;
    };
    
    for (i = (prev_given - 1); i >= 0; --i)
      {
        tmp = list;
        
        switch(arg_type) {
        case ARG_INT:
          (*((int **)field))[i + field_given] = tmp->arg.int_arg; break;
        case ARG_FLOAT:
          (*((float **)field))[i + field_given] = tmp->arg.float_arg; break;
        case ARG_DOUBLE:
          (*((double **)field))[i + field_given] = tmp->arg.double_arg; break;
        case ARG_STRING:
          (*((char ***)field))[i + field_given] = tmp->arg.string_arg; break;
        default:
          break;
        }        
        (*orig_field) [i + field_given] = list->orig;
        list = list->next;
        free (tmp);
      }
  } else { /* set the default value */
    if (default_value && ! field_given) {
      switch(arg_type) {
      case ARG_INT:
        if (! *((int **)field)) {
          *((int **)field) = (int *)malloc (sizeof (int));
          (*((int **)field))[0] = default_value->int_arg; 
        }
        break;
      case ARG_FLOAT:
        if (! *((float **)field)) {
          *((float **)field) = (float *)malloc (sizeof (float));
          (*((float **)field))[0] = default_value->float_arg;
        }
        break;
      case ARG_DOUBLE:
        if (! *((double **)field)) {
          *((double **)field) = (double *)malloc (sizeof (double));
          (*((double **)field))[0] = default_value->double_arg;
        }
        break;
      case ARG_STRING:
        if (! *((char ***)field)) {
          *((char ***)field) = (char **)malloc (sizeof (char *));
          (*((char ***)field))[0] = gengetopt_strdup(default_value->string_arg);
        }
        break;
      default: break;
      }
      if (!(*orig_field)) {
        *orig_field = (char **) malloc (sizeof (char *));
        (*orig_field)[0] = 0;
      }
    }
  }
}

int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  struct generic_list * grid_list = NULL;
  struct generic_list * somneuron_list = NULL;
  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  /* TODO: Why is this here? It is not used anywhere. */
  override = params->override;
  FIX_UNUSED(override);

  initialize = params->initialize;
  check_required = params->check_required;

  /* TODO: Why is this here? It is not used anywhere. */
  check_ambiguity = params->check_ambiguity;
  FIX_UNUSED(check_ambiguity);

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "inprefix",	1, NULL, 0 },
        { "outprefix",	1, NULL, 0 },
        { "intype",	1, NULL, 0 },
        { "outtype",	1, NULL, 0 },
        { "infile",	1, NULL, 0 },
        { "outfile",	1, NULL, 0 },
        { "dataset",	1, NULL, 0 },
        { "saveout",	1, NULL, 's' },
        { "overlap",	1, NULL, 0 },
        { "grid",	1, NULL, 'g' },
        { "threads",	1, NULL, 0 },
        { "bpp",	1, NULL, 'b' },
        { "refine",	1, NULL, 'r' },
        { "image",	1, NULL, 0 },
        { "negative",	1, NULL, 0 },
        { "attribute",	1, NULL, 'a' },
        { "attribute2",	1, NULL, 0 },
        { "decision",	1, NULL, 'd' },
        { "flood",	1, NULL, 'f' },
        { "output",	1, NULL, 'o' },
        { "lambda",	1, NULL, 'l' },
        { "lvec",	1, NULL, 0 },
        { "lvec2",	1, NULL, 0 },
        { "tree",	1, NULL, 't' },
        { "morphology",	1, NULL, 'm' },
        { "connectivity",	1, NULL, 'c' },
        { "imscale",	1, NULL, 0 },
        { "imscale2",	1, NULL, 0 },
        { "background",	1, NULL, 0 },
        { "verbosity",	1, NULL, 'v' },
        { "savetree",	1, NULL, 0 },
        { "somfile",	1, NULL, 0 },
        { "somsize",	1, NULL, 0 },
        { "somneuron",	1, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVs:g:b:r:a:d:f:o:l:t:m:c:v:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 's':	/* Save the output images. In case it needs to be deactivated for testing purposes.  */
        
        
          if (update_arg( (void *)&(args_info->saveout_arg), 
               &(args_info->saveout_orig), &(args_info->saveout_given),
              &(local_args_info.saveout_given), optarg, cmdline_parser_saveout_values, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "saveout", 's',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* Number of tiles horizontally, vertically, in depth, comma separated.  */
        
          if (update_multiple_arg_temp(&grid_list, 
              &(local_args_info.grid_given), optarg, 0, 0, ARG_INT,
              "grid", 'g',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* Define the dynamic range (if different from 8, 16 or 32 bits).  */
        
        
          if (update_arg( (void *)&(args_info->bpp_arg), 
               &(args_info->bpp_orig), &(args_info->bpp_given),
              &(local_args_info.bpp_given), optarg, 0, "8", ARG_INT,
              check_ambiguity, override, 0, 0,
              "bpp", 'b',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* Transform the data in 16-bit per pixel if original range is higher.  */
        
        
          if (update_arg( (void *)&(args_info->refine_arg), 
               &(args_info->refine_orig), &(args_info->refine_given),
              &(local_args_info.refine_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "refine", 'r',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* Choose the attribute to build the tree.  */
        
        
          if (update_arg( (void *)&(args_info->attribute_arg), 
               &(args_info->attribute_orig), &(args_info->attribute_given),
              &(local_args_info.attribute_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "attribute", 'a',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Choose the pruning rule to filter the tree.  */
        
        
          if (update_arg( (void *)&(args_info->decision_arg), 
               &(args_info->decision_orig), &(args_info->decision_given),
              &(local_args_info.decision_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "decision", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* Choose the used flooding technique (deprecated)..  */
        
        
          if (update_arg( (void *)&(args_info->flood_arg), 
               &(args_info->flood_orig), &(args_info->flood_given),
              &(local_args_info.flood_given), optarg, cmdline_parser_flood_values, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "flood", 'f',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* Choose the desired output.  */
        
        
          if (update_arg( (void *)&(args_info->output_arg), 
               &(args_info->output_orig), &(args_info->output_given),
              &(local_args_info.output_given), optarg, cmdline_parser_output_values, "filter", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "output", 'o',
              additional_error))
            goto failure;
        
          break;
        case 'l':	/* Lambda value.  */
        
        
          if (update_arg( (void *)&(args_info->lambda_arg), 
               &(args_info->lambda_orig), &(args_info->lambda_given),
              &(local_args_info.lambda_given), optarg, 0, "100", ARG_DOUBLE,
              check_ambiguity, override, 0, 0,
              "lambda", 'l',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Type of tree (Min or Max).  */
        
        
          if (update_arg( (void *)&(args_info->tree_arg), 
               &(args_info->tree_orig), &(args_info->tree_given),
              &(local_args_info.tree_given), optarg, cmdline_parser_tree_values, "max", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "tree", 't',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* Type of morphological operation (opening or closing).  */
        
        
          if (update_arg( (void *)&(args_info->morphology_arg), 
               &(args_info->morphology_orig), &(args_info->morphology_given),
              &(local_args_info.morphology_given), optarg, cmdline_parser_morphology_values, "opening", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "morphology", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* Type of connectivity (4 or 8 for 2D, 6 or 26 for 3D).  */
        
        
          if (update_arg( (void *)&(args_info->connectivity_arg), 
               &(args_info->connectivity_orig), &(args_info->connectivity_given),
              &(local_args_info.connectivity_given), optarg, cmdline_parser_connectivity_values, "4", ARG_INT,
              check_ambiguity, override, 0, 0,
              "connectivity", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'v':	/* Add verbose output.  */
        
        
          if (update_arg( (void *)&(args_info->verbosity_arg), 
               &(args_info->verbosity_orig), &(args_info->verbosity_given),
              &(local_args_info.verbosity_given), optarg, cmdline_parser_verbosity_values, "WARN", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "verbosity", 'v',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Prefix of the filenames of input tiles.  */
          if (strcmp (long_options[option_index].name, "inprefix") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->inprefix_arg), 
                 &(args_info->inprefix_orig), &(args_info->inprefix_given),
                &(local_args_info.inprefix_given), optarg, 0, "tile", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "inprefix", '-',
                additional_error))
              goto failure;
          
          }
          /* Prefix of the filenames for the output tiles.  */
          else if (strcmp (long_options[option_index].name, "outprefix") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->outprefix_arg), 
                 &(args_info->outprefix_orig), &(args_info->outprefix_given),
                &(local_args_info.outprefix_given), optarg, 0, "out", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "outprefix", '-',
                additional_error))
              goto failure;
          
          }
          /* filetype of the input tiles.  */
          else if (strcmp (long_options[option_index].name, "intype") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->intype_arg), 
                 &(args_info->intype_orig), &(args_info->intype_given),
                &(local_args_info.intype_given), optarg, 0, "pgm", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "intype", '-',
                additional_error))
              goto failure;
          
          }
          /* filetype of the output tiles.  */
          else if (strcmp (long_options[option_index].name, "outtype") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->outtype_arg), 
                 &(args_info->outtype_orig), &(args_info->outtype_given),
                &(local_args_info.outtype_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "outtype", '-',
                additional_error))
              goto failure;
          
          }
          /* Define how the input files are organized. 0: 1 file to be divided internally, 1: Each process takes a different file (see expected format names), 2: same file copied on all processes, 3: Combine RBG files.  */
          else if (strcmp (long_options[option_index].name, "infile") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->infile_arg), 
                 &(args_info->infile_orig), &(args_info->infile_given),
                &(local_args_info.infile_given), optarg, 0, "0", ARG_INT,
                check_ambiguity, override, 0, 0,
                "infile", '-',
                additional_error))
              goto failure;
          
          }
          /* Define how the output files are organized. 0: 1 single file is written, 2: Each process writes his tile (see expected format names).  */
          else if (strcmp (long_options[option_index].name, "outfile") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->outfile_arg), 
                 &(args_info->outfile_orig), &(args_info->outfile_given),
                &(local_args_info.outfile_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "outfile", '-',
                additional_error))
              goto failure;
          
          }
          /* Name of the dataset if using HDF5 files.  */
          else if (strcmp (long_options[option_index].name, "dataset") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->dataset_arg), 
                 &(args_info->dataset_orig), &(args_info->dataset_given),
                &(local_args_info.dataset_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "dataset", '-',
                additional_error))
              goto failure;
          
          }
          /* Save the output images. In case it needs to be deactivated for testing purposes.  */
          else if (strcmp (long_options[option_index].name, "overlap") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->overlap_arg), 
                 &(args_info->overlap_orig), &(args_info->overlap_given),
                &(local_args_info.overlap_given), optarg, cmdline_parser_overlap_values, "1", ARG_INT,
                check_ambiguity, override, 0, 0,
                "overlap", '-',
                additional_error))
              goto failure;
          
          }
          /* Number of threads to use.  */
          else if (strcmp (long_options[option_index].name, "threads") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->threads_arg), 
                 &(args_info->threads_orig), &(args_info->threads_given),
                &(local_args_info.threads_given), optarg, 0, "1", ARG_INT,
                check_ambiguity, override, 0, 0,
                "threads", '-',
                additional_error))
              goto failure;
          
          }
          /* Type of input: classic, rgb, lofar, sequence of 2D tiles to be combined internally.  */
          else if (strcmp (long_options[option_index].name, "image") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->image_arg), 
                 &(args_info->image_orig), &(args_info->image_given),
                &(local_args_info.image_given), optarg, 0, "classic", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "image", '-',
                additional_error))
              goto failure;
          
          }
          /* Transform the data in 16-bit per pixel if original range is higher.  */
          else if (strcmp (long_options[option_index].name, "negative") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->negative_arg), 
                 &(args_info->negative_orig), &(args_info->negative_given),
                &(local_args_info.negative_given), optarg, 0, "0", ARG_INT,
                check_ambiguity, override, 0, 0,
                "negative", '-',
                additional_error))
              goto failure;
          
          }
          /* Choose the second attribute for the pattern spectrum (only works with the inertia tensor so far).  */
          else if (strcmp (long_options[option_index].name, "attribute2") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->attribute2_arg), 
                 &(args_info->attribute2_orig), &(args_info->attribute2_given),
                &(local_args_info.attribute2_given), optarg, 0, "9", ARG_INT,
                check_ambiguity, override, 0, 0,
                "attribute2", '-',
                additional_error))
              goto failure;
          
          }
          /* Lambda vector for  attribute.  */
          else if (strcmp (long_options[option_index].name, "lvec") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->lvec_arg), 
                 &(args_info->lvec_orig), &(args_info->lvec_given),
                &(local_args_info.lvec_given), optarg, 0, "res/lvec.txt", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "lvec", '-',
                additional_error))
              goto failure;
          
          }
          /* Lambda vector for second attribute.  */
          else if (strcmp (long_options[option_index].name, "lvec2") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->lvec2_arg), 
                 &(args_info->lvec2_orig), &(args_info->lvec2_given),
                &(local_args_info.lvec2_given), optarg, 0, "res/lvec2.txt", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "lvec2", '-',
                additional_error))
              goto failure;
          
          }
          /* Scale for lvec file.  */
          else if (strcmp (long_options[option_index].name, "imscale") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->imscale_arg), 
                 &(args_info->imscale_orig), &(args_info->imscale_given),
                &(local_args_info.imscale_given), optarg, 0, "1.0", ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "imscale", '-',
                additional_error))
              goto failure;
          
          }
          /* Scale for lvec2 file.  */
          else if (strcmp (long_options[option_index].name, "imscale2") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->imscale2_arg), 
                 &(args_info->imscale2_orig), &(args_info->imscale2_given),
                &(local_args_info.imscale2_given), optarg, 0, "1.0", ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "imscale2", '-',
                additional_error))
              goto failure;
          
          }
          /* Account for background level in the pattern spectra.  */
          else if (strcmp (long_options[option_index].name, "background") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->background_arg), 
                 &(args_info->background_orig), &(args_info->background_given),
                &(local_args_info.background_given), optarg, 0, "0", ARG_INT,
                check_ambiguity, override, 0, 0,
                "background", '-',
                additional_error))
              goto failure;
          
          }
          /* Save the component tree. Each process will save its local tree, so it can be reused later (the same number of process will have to be used).  */
          else if (strcmp (long_options[option_index].name, "savetree") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->savetree_arg), 
                 &(args_info->savetree_orig), &(args_info->savetree_given),
                &(local_args_info.savetree_given), optarg, cmdline_parser_savetree_values, "0", ARG_INT,
                check_ambiguity, override, 0, 0,
                "savetree", '-',
                additional_error))
              goto failure;
          
          }
          /* Save the component tree. Each process will save its local tree, so it can be reused later (the same number of process will have to be used).  */
          else if (strcmp (long_options[option_index].name, "somfile") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->somfile_arg), 
                 &(args_info->somfile_orig), &(args_info->somfile_given),
                &(local_args_info.somfile_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "somfile", '-',
                additional_error))
              goto failure;
          
          }
          /* Save the component tree. Each process will save its local tree, so it can be reused later (the same number of process will have to be used).  */
          else if (strcmp (long_options[option_index].name, "somsize") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->somsize_arg), 
                 &(args_info->somsize_orig), &(args_info->somsize_given),
                &(local_args_info.somsize_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "somsize", '-',
                additional_error))
              goto failure;
          
          }
          /* Number of tiles horizontally, vertically, in depth, comma separated.  */
          else if (strcmp (long_options[option_index].name, "somneuron") == 0)
          {
          
            if (update_multiple_arg_temp(&somneuron_list, 
                &(local_args_info.somneuron_given), optarg, 0, 0, ARG_INT,
                "somneuron", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */


  update_multiple_arg((void *)&(args_info->grid_arg),
    &(args_info->grid_orig), args_info->grid_given,
    local_args_info.grid_given, 0,
    ARG_INT, grid_list);
  update_multiple_arg((void *)&(args_info->somneuron_arg),
    &(args_info->somneuron_orig), args_info->somneuron_given,
    local_args_info.somneuron_given, 0,
    ARG_INT, somneuron_list);

  args_info->grid_given += local_args_info.grid_given;
  local_args_info.grid_given = 0;
  args_info->somneuron_given += local_args_info.somneuron_given;
  local_args_info.somneuron_given = 0;
  
  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  free_list (grid_list, 0 );
  free_list (somneuron_list, 0 );
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
/* vim: set ft=c noet ts=8 sts=8 sw=8 tw=80 nojs spell : */
