version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
    # Add other tools or dependencies here if needed


# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub
