# .readthedocs.yaml

# Required version
version: 2

# Build documentation in the "docs" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
    # Add other tools or dependencies here if needed


# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Define the Python version and dependencies
# python:
#   version: "3.8"
#   install:
#     - method: pip
#       path: .
#     - requirements: docs/requirements.txt
